### ISSUE TITLE
updateSummaryState

### ISSUE THREAD

**Issue by p0nt** [slazarov/python-bittrex-websocket#4] opened 2017-12-11 06:52 UTC
So how can I get full feed from all tickets (updateSummaryState) in a simple script?

The example you've provided a few weeks ago is gone:
https://github.com/slazarov/python-bittrex-websocket/blob/master/bittrex_websocket/summary_state.py

**Comment by slazarov** [comment] 2017-12-11 10:28
@p0nt v0.0.2 introduced new subscription methods which are significantly more user friendly. I suggest checking the new documentation briefly.

As per your request I have added a sample updateSummaryState script in the examples folder.
https://github.com/slazarov/python-bittrex-websocket/blob/master/bittrex_websocket/examples/ticker_updates.py

If it's working for you, make sure to close the issue.

**Comment by p0nt** [comment] 2017-12-13 10:35
This one gives the following error:

> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/signalr/_connection.py", line 53, in wrapped_listener
    listener()
  File "/usr/local/lib/python2.7/dist-packages/signalr/transports/_ws_transport.py", line 43, in _receive
    self._handle_notification(notification)
  File "/usr/local/lib/python2.7/dist-packages/signalr/transports/_transport.py", line 50, in _handle_notification
    self._connection.received.fire(**data)
  File "/usr/local/lib/python2.7/dist-packages/signalr/events/_events.py", line 15, in fire
    handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/signalr/hubs/_hub.py", line 40, in handle
    self.__handlers[method].fire(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/signalr/events/_events.py", line 15, in fire
    handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bittrex_websocket/websocket_client.py", line 835, in _on_ticker_update
    self.updateSummaryState.on_change(ticker_updates)
  File "/usr/local/lib/python2.7/dist-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "./test2.py", line 27, in on_ticker_update
    name = msg['MarketName']
KeyError: 'MarketName'

**Comment by slazarov** [comment] 2017-12-13 11:04
Can you provide the code you are executing?

You are right about `updateSummaryState`, on the Bittrex end it subscribes to all tickers and this is what the socket receives as raw data. I have added the functionality to be able to receive information only about the tickers you are interested in. Example diagram:

> invoke updateSummaryState
>> receive raw data for the tickers that have changes
>>> filter the raw data and leave only the tickers you are interested in
>>>> receive the change at `on_ticker_update`

However, I believe what you are trying to accomplish is adequate and reasonable, so in the next update I will add the functionality: when you don't specify any tickers `subscribe_to_ticker_update`, you will receive all updates.

**Comment by p0nt** [comment] 2017-12-13 11:49
Would be awesome yeah!

So I am just looking to retrieve exactly the same information as this:
https://bittrex.com/api/v1.1/public/getmarketsummaries

But then in a websocket :)

**Comment by slazarov** [comment] 2017-12-13 14:10
In your previous comment, were you getting the error because you were not specifying a ticker?

**Comment by p0nt** [comment] 2017-12-13 14:20
No, it came when I used a ticker :)

Just copy pasted your code 100%

**Comment by slazarov** [comment] 2017-12-13 14:30
Are you getting the issue constantly or was it a one time thing? I am trying to reproduce it but works fine on my end. The msg from `on_ticker_update` is:
```
{
  "MarketName": "BTC-NEO",
  "High": 0.00295,
  "Low": 0.00217701,
  "Volume": 1831960.21258868,
  "Last": 0.00273,
  "BaseVolume": 4633.06808936,
  "TimeStamp": "2017-12-13T14:25:51.763",
  "Bid": 0.00272773,
  "Ask": 0.00272998,
  "OpenBuyOrders": 5420,
  "OpenSellOrders": 28978,
  "PrevDay": 0.00221,
  "Created": "2016-10-26T01:28:31.96"
}
```
Hence msg['MarketName] exists.
If the error keeps popping up, please debug it and check what's in the msg.

**Comment by slazarov** [comment] 2017-12-13 15:13
@p0nt,
 try
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git@v0.0.5`
and call `subscribe_to_ticker_update()` without parameters. You should receive the updates for all tickers now.

**Comment by p0nt** [comment] 2017-12-14 06:53
tried, gives errors:

https://paste.2215.nl/view/Xozr8536OlnDy

#!/usr/bin/python

from __future__ import print_function
import time
from bittrex_websocket.websocket_client import BittrexSocket

def main():
  class MySocket(BittrexSocket):
    def on_open(self):
      self.ticker_updates_container = {}

    def on_ticker_update(self, msg):
      name = msg['MarketName']
      if name not in self.ticker_updates_container:
        self.ticker_updates_container[name] = msg
        print('Just received ticker update for {}.'.format(name))

  ws = MySocket()

  ws.subscribe_to_ticker_update()

  while True:
    time.sleep(1)
#  ws.disconnect()

if __name__ == "__main__":
    main()

**Comment by slazarov** [comment] 2017-12-14 21:41
name = msg['MarketName'] should apply when you specify a ticker, when you don’t pass one, the msg structure is different. The example file is for the first case that’s why it doesn’t work. Change the on_ticker_update content to say print(msg) and it will work.

**Comment by p0nt** [comment] 2017-12-20 12:18
awesome ty that works!

Now I will just have to figure out a way without that ugly sleep and just get updates when there are new updates.

**Comment by slazarov** [comment] 2017-12-20 12:33
You can use a queue for that. You can even check my source code because i use them heavily.
Is this issue solved, can I close it?

**Comment by slazarov** [comment] 2017-12-30 13:17
Closing because initial issue was solved.

**Closed by slazarov** 2017-12-30 13:17 UTC
Labels: enhancement, good first issue
