### ISSUE TITLE
Reconnect and subsciption not re-established

### ISSUE THREAD

**Issue by ccullin** [slazarov/python-bittrex-websocket#34] opened 2018-02-11 14:21 UTC
websocket works really well slazarov.  I have a headless data collector and am testing different scenarios with latest version available form pip install.    I have am subscribing to Trades for a single currently only to keep testing simple and when I remove the LAN connection the socket does not fully recover.

Early today reconnect would eventually defer to the Watchdog, but I have change versions and config since then - now the connection recovers when LAN restored, but the subscription is not re-established.

I cannot capture an exception and on_error is not called.  I know you are working on Reconnect, is this something you are aware of?

Also - an Exception is thrown on LAN disconnect but it does not appear to be causing issues.  
Websocket._exceptions.WebSocketConnectionsClosedException: Connection is already close.

This is thrown several times and is repeatable with a LAN disconnect during Trade subscription.

**Comment by slazarov** [comment] 2018-02-12 06:13
Hi, can you please check this issue to see if that will provide you with additional info. I am working on reconnection, sadly can’t give an ETA. 

https://github.com/slazarov/python-bittrex-websocket/issues/35

**Comment by rightx2** [comment] 2018-02-12 07:56
#35 Same problem! why does that happen?

**Comment by ccullin** [comment] 2018-02-12 10:21
Hi,  The exception is related, but the exception by itself does not appear to be a problem.  Ok, it's not graceful, but the socket does re-establish, at least in my testing.    The problem is that the subscription is not re-subscribed to.

I note you are working on this - if you need anything let me know.  I will continue to investigate.

**Comment by slazarov** [comment] 2018-02-12 19:18
The problem is that the reconnection mechanism is triggered within `_init_connection`, so it there is an exception outside that method, it will not reconnect.

@ccullin can you post a log of when you get this 

> The problem is that the subscription is not re-subscribed to.

**Comment by slazarov** [comment] 2018-02-12 20:00
Too many issues for the same problem. Closing this one. All errors related to this issue will be discussed here:
https://github.com/slazarov/python-bittrex-websocket/issues/35

**Closed by slazarov** 2018-02-12 20:00 UTC
